-- Haskell module generated by the BNF converter

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Grammar.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Grammar.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Grammar.Abs.Ident -> Result
transIdent x = case x of
  Grammar.Abs.Ident string -> failure x

transProgram :: Grammar.Abs.Program -> Result
transProgram x = case x of
  Grammar.Abs.Program topdefs -> failure x

transTopDef :: Grammar.Abs.TopDef -> Result
transTopDef x = case x of
  Grammar.Abs.FnDef type_ ident args block -> failure x
  Grammar.Abs.GlobDecl type_ items -> failure x
  Grammar.Abs.GlobFinDecl type_ items -> failure x

transArg :: Grammar.Abs.Arg -> Result
transArg x = case x of
  Grammar.Abs.Arg type_ ident -> failure x

transBlock :: Grammar.Abs.Block -> Result
transBlock x = case x of
  Grammar.Abs.Block stmts -> failure x

transStmt :: Grammar.Abs.Stmt -> Result
transStmt x = case x of
  Grammar.Abs.Empty -> failure x
  Grammar.Abs.BStmt block -> failure x
  Grammar.Abs.Decl type_ items -> failure x
  Grammar.Abs.DeclFinal type_ items -> failure x
  Grammar.Abs.Ass ident expr -> failure x
  Grammar.Abs.Incr ident -> failure x
  Grammar.Abs.Decr ident -> failure x
  Grammar.Abs.Ret expr -> failure x
  Grammar.Abs.VRet -> failure x
  Grammar.Abs.Cond expr stmt -> failure x
  Grammar.Abs.CondElse expr stmt1 stmt2 -> failure x
  Grammar.Abs.While expr stmt -> failure x
  Grammar.Abs.SExp expr -> failure x
  Grammar.Abs.FnInDef type_ ident args block -> failure x
  Grammar.Abs.ConstFor type_ ident expr1 expr2 stmt -> failure x
  Grammar.Abs.Break -> failure x
  Grammar.Abs.Continue -> failure x
  Grammar.Abs.Print expr -> failure x

transItem :: Grammar.Abs.Item -> Result
transItem x = case x of
  Grammar.Abs.NoInit ident -> failure x
  Grammar.Abs.Init ident expr -> failure x

transType :: Grammar.Abs.Type -> Result
transType x = case x of
  Grammar.Abs.Int -> failure x
  Grammar.Abs.Str -> failure x
  Grammar.Abs.Bool -> failure x
  Grammar.Abs.Void -> failure x
  Grammar.Abs.FuncType types type_ -> failure x

transExpr :: Grammar.Abs.Expr -> Result
transExpr x = case x of
  Grammar.Abs.EVar ident -> failure x
  Grammar.Abs.ELitInt integer -> failure x
  Grammar.Abs.ELitTrue -> failure x
  Grammar.Abs.ELitFalse -> failure x
  Grammar.Abs.EApp ident exprs -> failure x
  Grammar.Abs.EString string -> failure x
  Grammar.Abs.ELambda args type_ block -> failure x
  Grammar.Abs.Neg expr -> failure x
  Grammar.Abs.Not expr -> failure x
  Grammar.Abs.EMul expr1 mulop expr2 -> failure x
  Grammar.Abs.EAdd expr1 addop expr2 -> failure x
  Grammar.Abs.ERel expr1 relop expr2 -> failure x
  Grammar.Abs.EAnd expr1 expr2 -> failure x
  Grammar.Abs.EOr expr1 expr2 -> failure x

transAddOp :: Grammar.Abs.AddOp -> Result
transAddOp x = case x of
  Grammar.Abs.Plus -> failure x
  Grammar.Abs.Minus -> failure x

transMulOp :: Grammar.Abs.MulOp -> Result
transMulOp x = case x of
  Grammar.Abs.Times -> failure x
  Grammar.Abs.Div -> failure x
  Grammar.Abs.Mod -> failure x

transRelOp :: Grammar.Abs.RelOp -> Result
transRelOp x = case x of
  Grammar.Abs.LTH -> failure x
  Grammar.Abs.LE -> failure x
  Grammar.Abs.GTH -> failure x
  Grammar.Abs.GE -> failure x
  Grammar.Abs.EQU -> failure x
  Grammar.Abs.NE -> failure x
